branch_protection_rules:
  - pattern: main
    required_status_checks:
      strict: true
      contexts:
        - security
        - test
        - lint
        - docs
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      require_last_push_approval: true
    enforce_admins: true
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true
    lock_branch: true
    allow_fork_syncing: true 