version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "HeavenzFire"
    assignees:
      - "HeavenzFire"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "numpy"
        versions: ["1.24.0", "1.24.1"]
      - dependency-name: "torch"
        versions: ["2.0.0", "2.0.1"]
      - dependency-name: "qiskit"
        versions: ["0.40.0", "0.40.1"] 