# Security Configuration

# Encryption Settings
encryption:
  algorithm: "AES-256-GCM"
  key_length: 32
  iv_length: 12
  tag_length: 16

# Authentication Settings
authentication:
  jwt_secret: "your_jwt_secret_here"
  token_expiry: 3600  # seconds
  refresh_token_expiry: 86400  # seconds
  password_hash_rounds: 12

# API Security
api_security:
  rate_limit: 100  # requests per minute
  cors_origins:
    - "https://yourdomain.com"
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Requested-With"

# Network Security
network_security:
  ssl_enabled: true
  ssl_cert_path: "/path/to/cert.pem"
  ssl_key_path: "/path/to/key.pem"
  firewall_rules:
    - action: "allow"
      protocol: "tcp"
      port: 443
    - action: "allow"
      protocol: "tcp"
      port: 80

# Data Protection
data_protection:
  encryption_at_rest: true
  backup_frequency: "daily"
  retention_period: 30  # days
  sensitive_fields:
    - "password"
    - "api_key"
    - "token"
    - "credit_card"

# Monitoring
monitoring:
  log_level: "INFO"
  alert_thresholds:
    failed_login_attempts: 5
    suspicious_activity: 3
  notification_channels:
    - "email"
    - "slack"
  retention_period: 90  # days

# Quantum Security
quantum_security:
  post_quantum_algorithm: "Kyber-768"
  quantum_key_distribution: true
  quantum_random_number_generator: true

# Ethical Constraints
ethical_constraints:
  suffering_prevention_threshold: 0.8
  transparency_threshold: 0.7
  collective_good_threshold: 0.9
  max_threat_level: 0.07

# Device Security
device_security:
  bluetooth:
    pairing_timeout: 30  # seconds
    max_paired_devices: 5
  gps:
    location_update_interval: 60  # seconds
    accuracy_threshold: 10  # meters
  mobile_devices:
    max_connections: 100
    session_timeout: 3600  # seconds

# Backup and Recovery
backup:
  frequency: "daily"
  retention: 30  # days
  encryption: true
  locations:
    - "local"
    - "cloud"
  verification: true 