name: Quantum Performance Benchmarking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  quantum-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qiskit[all] pennylane cirq mitiq
          pip install pytest pytest-benchmark

      - name: Run Quantum Volume Tests
        run: |
          python -m pytest tests/quantum/test_quantum_volume.py -v

      - name: Run Algorithm Benchmarks
        run: |
          python -m pytest tests/quantum/test_quantum_algorithms.py --benchmark-only

      - name: Run Error Correction Tests
        run: |
          python -m pytest tests/quantum/test_error_correction.py -v

      - name: Generate Benchmark Report
        run: |
          python scripts/generate_benchmark_report.py

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: quantum-benchmark-results
          path: |
            benchmark-results.json
            quantum-volume-report.json
            error-correction-metrics.json 
