name: Dependency Management

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update dependencies
        uses: actions/dependency-review-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run security audit
        run: |
          pip install safety
          safety check --full-report

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            Automated dependency updates:
            - Updated Python package dependencies
            - Security audit results
          branch: "dependencies/update-$(date +%Y%m%d)"
          base: main

  notify:
    needs: update-dependencies
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send update notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: dependencies
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Dependency Update Status
          SLACK_MESSAGE: "Dependency update process completed. Check the pull request for details." 