name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily scan

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit semgrep
          
      - name: Run Safety (Python dependency checker)
        run: safety check --full-report
        
      - name: Run Bandit (Python security linter)
        run: bandit -r src/ -ll
        
      - name: Run Semgrep
        run: semgrep --config auto src/
        
      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: |
            safety-report.txt
            bandit-report.txt
            semgrep-report.txt 