name: Framework Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run validation tests
      run: |
        python -m pytest tests/validate_framework.py -v
        
    - name: Run quantum consciousness tests
      run: |
        python -m pytest tests/test_sovereign_flow.py -v
        
    - name: Run sacred geometry tests
      run: |
        python -m pytest tests/metaphysical/mathematics/core/test_validation.py -v
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 